config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Users could signup multiple times
  resources :users

  # Users can only make one session
  resource :session



  get "about", to: "page#about" 

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord

  validates :name, presence: true
  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  
  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # make @current_user available to views
  helper_method :current_user, :is_logged_in

  # run this on every single page
  before_action :current_user, :is_logged_in
  def current_user
    if is_logged_in
      @current_user = User.find(session[:user_id])
    else
      @current_user = nil
      
    end
    @current_user 
    
  end
  
  def is_logged_in
    session[:user_id].present?
  end

  def reset_session
    @_request.reset_session
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def  new
    
  end
  
  def show
    reset_session    
    flash[:success] = "You are now logged out!"
    redirect_to root_path
  end
    
  def create
    
    @username = form_params[:username]
    @password = form_params[:password]

    @user = User.find_by(username: @username).try(:authenticate, @password)

    if @user.present?
      session[:user_id] = @user.id
      
      flash[:success] = "You are now logged in!"

      redirect_to root_path

    else
      render "new"
    end

  end

  # def destroy
  #   @_request.reset_session

  #   flash[:success] = "You are now logged out!"

  #   redirect_to root_path
  # end
  

  def form_params
    params.require(:session).permit(:username, :password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(form_params)

    # Check if user save
    if @user.save

      # Keep hold of that user
      session[:user_id] = @user.id

      # Let the user knnow they signup
      flash[:success] = "Welcome to Pictons"

      redirect_to root_path
    else
      render "new"
    end
  end

  def form_params
    params.require(:user).permit(:name,:username,:email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pictons</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>
  <body>

    <% if flash[:success].present? %>
      <div class="success">
        <%= flash[:success] %>
      </div>
    <% end %>

  <header>
  
    <nav>
  

      <% if is_logged_in %>
      
        Username is <%= @current_user.username %><br>
        User Id is <%= session[:user_id] %>

        <%= link_to "Log out", session_path, method: :delete %>

      <% else %>

        <%= link_to "Sign up", new_user_path %>
        <%= link_to "Log in", new_session_path %>

      <% end %>
      
    </nav>
  </header>

    <%= yield %>

  </body>
</html>

app/views/pages/home.html.erb
<h1>Source</h1>

<p>
  <%= link_to "Sign up", new_user_path, class: "button" %>
  <%= simple_format link_to "Log in", new_session_path, class: "button button-outline" %>

</p>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= simple_form_for @user do |f| %>

<%= f.input :name %>
<%= f.input :username %>
<%= f.input :email %>
<%= f.input :password %>
<%= f.input :password_confirmation %>

<%= f.button :submit %>

<% end %>